### ISSUE TITLE
Campos personalizados de CPF/CNPJ

### ISSUE THREAD

**Issue by lucianozanita** [gofas/whmcs-gerencianet-boleto#1]
Estou encontrando uma dificuldade em ter vários campos personalizados, estive observando o código e indica na linha:
$cpf = preg_replace('/[^\da-z]/i', '', $params['clientdetails']['customfields1']);// CPF quando há apenas um campo personalizado

Que é quando apenas há um campo personalizado, mesmo o campo meu do cpf sendo o customfields1 ele acusa como resultado nulo(zerado), mesmo estando preenchido.
Acho interessante em ter uma opção na administração do módulo onde pode-se escolher qual campo personalizado usaria para preencher.

**Comment by mauriciogofas** [comment]
No momento, o módulo reconhece os dois primeiros campos personalizados como CPF e CNPJ,
sendo o campo ID 1 o CPF e o campo ID 2 o CNPJ, o comentário no código "CPF quando há apenas um campo personalizado
" é de uma versão anterior, quando ainda não gerava cobrança com CNPJ. Observe que eu atualizei os comentários na linha 110 e 111 do arquivo `gofasgerencianetboleto.php`.

Você tem duas opções no momento:
1) mudar a ordem de exibição dos seus campos personalizados, preenchendo com 0(zero) a opção "Ordem de Exibição" do campo CPF
e com 1 a opção "Ordem de Exibição" do campo CNPJ. Como na imagem a seguir: http://prntscr.com/bho097

Para saber com certeza o ID do customfield que está sendo retornado, ative a opção debug do módulo e verifique as informações que serão exibidas no topo da tela, no array `[customfields1]`, esse trecho da consulta deve ter essa estrutura:

`[customfields1] => 414.538.495-48
            [customfields] => Array
                (
                    [0] => Array
                        (
                            [id] => 1
                            [value] => 414.538.495-48
                        )

                    [1] => Array
                        (
                            [id] => 2
                            [value] => 64.234.595/0001-22
                        )

                )

            [customfields2] => 64.234.595/0001-22`

2) A segunda opção, se vc não deseja mudar a ordem dos seus campos personalizados, é editar a linha 110 e 111 do arquivo `gofasgerencianetboleto.php`, mudando para o ID dos seus campos, exemplo:
 
Digamos que o CPF é o campo ID 4 e o CNPJ é o campo id 5, essas duas linhas devem ficar assim:

`$cpf = preg_replace('/[^\da-z]/i', '', $params['clientdetails']['customfields1']['4']['value']);// Quarto campo personalizado
  $cnpj = preg_replace('/[^\da-z]/i', '', $params['clientdetails']['customfields']['5']['value']); // Quinto campo personalizado`

Por favor, me deixe saber se funcionou, agradeço!

A opção para selecionar os campos personalizados nas configurações do módulo será adicionada em breve =)

**Comment by lucianozanita** [comment]
Obrigado deu tudo muito certo.
Gostaria só de dar algumas dicas como:
O botão "Visualizar Boleto" acrescente um <br/> antes dele para que se encaixe perfeitamente na fatura, aqui tive que fazer para que o botão nao sobrescreve-se o texto de "Em Aberto" da fatura.

**Comment by mauriciogofas** [comment]
Fico feliz que conseguiu rodar o módulo!
Não entendi "O botão "Visualizar Boleto" acrescente um",
de qualquer forma, o tamanho recomendado da imagem do botão é de 160x43px, com essa medida o botão na fatura ficará como na imagem a seguir:
http://prntscr.com/bixqh5

**Comment by mauriciogofas** [comment]
Foram adicionadas ao módulo as opções para definir a ordem de exibição dos campos personalizados 🤓
