### ISSUE TITLE
Gerando varias transações zeradas

### ISSUE THREAD

**Issue by lucianozanita** [gofas/whmcs-gerencianet-boleto#10]
Olá, estou tendo um grande problema com o módulo, ele esta gerando todos os dias várias transações no WHMCS no qual ficam todas com valor zerado, e isso tem causado varias transações sem nome pela Api do GerenciaNET, provavelmente pode ser algum bug.
Veja como fica o gerencianet e o WHMCS.

GerenciaNET: http://prnt.sc/cab9h8
lembrando que isso é sozinho.

WHMCS na fatura do cliente: http://prntscr.com/cab9x1
Isso é porque a fatura é nova, uma fatura mais antiga pode chegar a ter um histórico gigante.

**Comment by cunningham-br** [comment]
Ja havia reparado nisso parece que quando tem erro no CPF ouo CNPJ e que ocorro isso em testes que u fiz

**Comment by lucianozanita** [comment]
Aqui é sem erro mesmo, gerando a fatura, funcionando perfeito, o problema é que cada dia o bendito gera uma transação.

**Comment by cunningham-br** [comment]
Vi no git oficial que teve uma alteração no Request.php
talvez seja isso removeram estas linhas
"private $certified_path;" (linha 18)
e estas
"            if($this->certified_path){
                $this->client->setDefaultOption("verify", $this->certified_path);
            }" (linhas 41,42 e 43)

**Comment by mauriciogofas** [comment]
Olá @lucianozanita.
Não há nenhum erro, cada vez que a fatura gera um novo boleto, uma nova transação é gravada no whmcs. 
O módulo gera um novo boleto com vencimento para o próximo dia quando o cliente acesa a fatura novamente após o vencimento, mas se vc acessar a fatura antes do vencimento o módulo vai exibir o boleto gerado anteriormente e nenhuma nova transação é gerada.
