### ISSUE TITLE
Taxas cobradas não aparece no retorno do pagamento

### ISSUE THREAD

**Issue by cunningham-br** [gofas/whmcs-gerencianet-boleto#11]
Verifiquei também que no retorno do pagamento efetuado nao computa as taxas descontadas pelo gerencianet aplicando assim o valor integral da fatura 
alguém sabe como colocar para pegar o valor da taxa e computar corretamente

**Comment by mauriciogofas** [comment]
O Gerencianet não retorna essa informação (diferente do PayPal por ex).
