### ISSUE TITLE
Class 'Gerencianet\Gerencianet' not found

### ISSUE THREAD

**Issue by Vision70** [gofas/whmcs-gerencianet-boleto#12]
Olá,

Instalei o modulo e fui tentar gerar o boleto através da fatura e obtive este erro:

Fatal error: Class 'Gerencianet\Gerencianet' not found in /home/goldlea/public_html/clientes/modules/gateways/gofasgerencianetboleto.php on line 23

Os arquivos foram copiados para as pastas indicadas.

Alguem já enfrentou esse tipo de problema?

Obrigado,

Marcelo

**Comment by mauriciogofas** [comment]
Olá Marcelo,
Vc esta instalando o módulo pela primeira vez ou atualizando?
Verificou se a versão do seu whmcs e PHP são compatíveis com o módulo?
Esse erro acontece quando algum arquivo da pasta SDK não é encontrado, neste link tem algumas opções que vc pode tentar para diagnosticar:
https://portaldohost.com.br/forum/topic/20358-m%C3%B3dulo-whmcs-gerencianet-nova-api-boleto/?do=findComment&comment=187945

Tente verificar se todos os arquivos estão ok e me avise se descobrir a solução, por favor.

**Comment by mauriciogofas** [comment]
Olá @Vision70,
resolvido o erro, teste, por favor.
Aguardo sua resposta, dando certo ou não.
Se o seu problema foi resolvido, lembre-se de fechar o issue, por favor ;)

**Comment by Vision70** [comment]
Oi Mauricio,

O problema foi resolvido. 

Obrigado

**Comment by mauriciogofas** [comment]
Que bom!
Se precisar pode escrever de novo ou reabrir o issue.
