### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by hukunoz** [gofas/whmcs-gerencianet-boleto#13]
Parse error: syntax error, unexpected '<<' (T_SL) in /home/yes/www/clients/modules/gateways/gofasgerencianetboleto/params.php on line 127

Verifiquei que foi incluído um código esquisito no módulo:

eval(base64_decode("JG9wdGlvbnMgPSBbImNsaWVudF9pZCI9PiRjbGllbnRpZCwiY2xpZW50X3NlY3JldCI9PiRjbGllbnRzZWNyZXQsInNhbmRib3giPT4kc2FuZGJveCwiZGVidWciPT4kZGVidWcsInBhcnRuZXJfdG9rZW4iPT4iYmFhZjViOTVkNTU0MzM4OTBiZDgzNWNmMDA2NzcyYjk0NjJiZGU4ZiJdOw=="));

Pelo que verifiquei no site ( https://www.tools4noobs.com/online_php_functions/base64_decode/ ) o resultado seria:

$options = ["client_id"=>$clientid,"client_secret"=>$clientsecret,"sandbox"=>$sandbox,"debug"=>$debug,"partner_token"=>"baaf5b95d55433890bd835cf006772b9462bde8f"];

O que significa esse partner_token?

**Comment by mauriciogofas** [comment]
Não é um erro, apenas um aviso do php, qual versão do vc está executando?
O partner_token é meu id de parceiro Gerencianet (https://gerencianet.com.br/parceiros/), isso é usado para o suporte diferenciar as transações criadas pelo meu módulo, assim todo suporte relacionado ao meu módulo é repassado para a Gofas.
Codifiquei esse trecho apenas para não ficar estampado nos resultados das buscas.
Quando encontrar a solução, por favor, feche o issue, ok?

**Comment by hukunoz** [comment]
PHP 5.6, linhas:

<<<<<<< HEAD
=======
$sandbox					= $params['testmode'];
if ($sandbox) {
	$clientid				= $params['clientidsandbox'];
	$clientsecret				= $params['clientsecretsandbox'];
} elseif (!$sandbox) {
	$clientid				= $params['clientid'];
	$clientsecret				= $params['clientsecret'];
}
eval(base64_decode("JG9wdGlvbnMgPSBbImNsaWVudF9pZCI9PiRjbGllbnRpZCwiY2xpZW50X3NlY3JldCI9PiRjbGllbnRzZWNyZXQsInNhbmRib3giPT4kc2FuZGJveCwiZGVidWciPT4kZGVidWcsInBhcnRuZXJfdG9rZW4iPT4iYmFhZjViOTVkNTU0MzM4OTBiZDgzNWNmMDA2NzcyYjk0NjJiZGU4ZiJdOw=="));
>>>>>>> origin/master

**Comment by hukunoz** [comment]
baixei novamente os arquivos e resolveu.

Agora estou com outro problema.

**Comment by mauriciogofas** [comment]
Legal, gratidão por reportar!
Se tiver alguma dificuldade com essa questão novamente pode reabrir o _issue_.
