### ISSUE TITLE
Fatura em atraso

### ISSUE THREAD

**Issue by hukunoz** [gofas/whmcs-gerencianet-boleto#14]
Se porventura ocorrer alteração do valor da fatura o módulo não atualiza a transação.

Exemplo, gerei uma fatura de R$ 10,00 e após 4 dias meu cliente não pagou, o sistema adicionou R$ 4,00 de multa/juros ou seja R$ 14.00, o cliente continua pagando apenas R$ 10.00.

**Comment by mauriciogofas** [comment]
Oi @hukunoz, gratidão por compartilhar sua dúvida!

A atualização de hoje inclui a opção "Cancelar boleto e gerar um novo", para o caso do cliente acessar a fatura para gerar um novo boleto após o vencimento da fatura.

Com essa opção ativa, se você instruir o caixa nas instruções do boleto a não aceitar pagamento após o vencimento, o cliente terá que acessar a fatura novamente para obter uma segunda via, nesse acesso o módulo vai gerar um novo boleto com o valor atualizado, de acordo com o novo valor da fatura.

Essa foi a forma que encontramos, pois a API da Gerencianet não permite alterar o valor de um boleto, apenas a sua data de vencimento.

**Comment by hukunoz** [comment]
Como posso efetuar esse teste? 

Acabei de simular uma fatura e atualizou apenas a data do boleto, o valor continuou o antigo.

Não é possível efetuar um ajuste automático no vencimento do boleto em caso da fatura estiver vencida? Pois ocorre o erro:

Falha ao gerar o boleto - 1ª tentativa (API externa - Gerencianet).
3500037invalid_datearray(2) {
  ["property"]=>
  string(9) "expire_at"
  ["message"]=>
  string(87) "A propriedade [expire_at] informada é inválida. Deve ser maior ou igual a data atual."
}

Atualmente eu preciso que isso seja automático e não ocorra alteração manual.

**Comment by mauriciogofas** [comment]
Isso acontece automaticamente @hukunoz, depois que a fatura venceu, no novo acesso a data do boleto associado à fatura é atualizada. Vc também pode escolher por cancelar o boleto e gerar um novo após o vencimento, mas lembre de colocar nas instruções "Sr. Caixa, não aceitar pagamento após vencimento".

O erro acima pode estar relacionado à configuração "Dias adicionais à data de vencimento do Boleto".

Tenha bastante atenção com as configurações, algumas trabalham em conjunto e deve se levar em consideração às instruções do boleto, que são uma "configuração" para o caixa.

Se quiser entra no nosso slack que eu te ajudo rapidinho pelo chat:
https://gofas.net/slack/

**Comment by hukunoz** [comment]
O campo "Dias adicionais à data de vencimento do Boleto" está em branco, vou efetuar outros testes.

O arquivo hooks.php serve para que?

**Comment by mauriciogofas** [comment]
Esse campo não deve ficar em branco, coloque 0 (zero) se deseja gerar a segunda via dos boletos com a data de vencimento para o mesmo dia em que o boleto foi gerado.

O arquivos hooks.php é uma integração (beta) com o módulo de gerenciamento remoto que estamos desenvolvendo para interagir com as transações registradas na API GN diretamente no painel do whmcs (https://github.com/gofas/whmcs-gerencianet-dashboard).

Mas o projeto mudou e esse arquivo não é mais necessário, ele será removido do repositório na próxima atualização, você pode excluir ele.

Feche o tópico quando estiver tudo esclarecido, por favor, vc pode reabrir ele se surgir alguma dúvida no futuro.

Gratidão, até logo!
