### ISSUE TITLE
Erro: 4600470 N N ?

### ISSUE THREAD

**Issue by lucapaju** [gofas/whmcs-gerencianet-boleto#15]
Por favor, estou fazendo testes de geração de boleto e um dos clientes está apresentando o erro:
Erro: 4600470 N N, no LOG do API na gerencianet, ele aparece como “sucesso”.

  *\* Já reinformei os dados de cadastro, etc... deixando igual a outro que o boleto é gerado normalmente, mas nada de aparecer o botão de pagamento para esta conta especifica.

[]'s Luiz Passarelli

**Comment by mauriciogofas** [comment]
Como esse _issue_ não teve resposta ou mais informações, podemos concluir que a sua dificuldade foi solucionada @lucapaju?
Vou fechar o _issue_ mas você pode reabrir se tiver algo a acrescentar à essa questão.
