### ISSUE TITLE
Fatal error: Cannot redeclare calcule_amount()

### ISSUE THREAD

**Issue by TecSecret** [gofas/whmcs-gerencianet-boleto#16]
Bom dia Gofas,

Em primeiro lugar parabéns pelo trabalho.

No WHMCS v7.0.1 apresenta o seguinte erro.

Fatal error: Cannot redeclare calcule_amount() (previously declared in pastadowhmcs/modules/gateways/gofasgerencianetboleto/params.php:172) in pastadowhmcs/modules/gateways/gofasgerencianetboleto/params.php on line 172

Um grande abraço

**Comment by mauriciogofas** [comment]
Bom dia @TecSecret, gratidão pelo feedback!
Acredito que esse erro está acontecendo em casos bem específicos, quando se aplica taxas fixas aos boletos. Só pra eu tentar entender melhor: Vc configurou taxa ou desconto de valor fixo (R$)?

Ps.: Tudo bem se eu transferir sua questão para o [fórum do módulo](https://gofas.net/forums/forum/whmcs/modulo-gerencianet-dashboard-para-whmcs/)?
É que em breve eu vou fechar a aba _issues_ para concentrar o suporte no gofas.net.

**Comment by mauriciogofas** [comment]
Corrigimos isso na versão[ 0.2.3](https://github.com/gofas/whmcs-gerencianet-boleto/releases/tag/0.2.3), acredito que conseguimos prever todas as combinações possíveis de situações e configurações que poderiam causar falha, em especial na área que trata de descontos, taxas, juros e todos os cálculos realizados pelo módulo.
Depois que vc testar compartilha aqui com a gente o seu feedback ;)
Vou fechar o _issue_ mas vc pode reabrir novamente se precisar.
