### ISSUE TITLE
Cancelamento de Boleto via API

### ISSUE THREAD

**Issue by lucianozanita** [gofas/whmcs-gerencianet-boleto#2]
Olá, gostaria de sugerir algo muito importante que é necessário nessa nova api do gerencianet que é o cancelamento de boleto, você não conseguiria acrescentar essa função?
Pois pelo painel do gerencianet não existe forma de cancelar a mesma a não ser pela api.
por exemplo, pode ser algo simples que só envie a solicitação pela api para cancelar o boleto que foi gerado.

**Comment by mauriciogofas** [comment]
Olá,
pretendo acrescentar o cancelamento automático do Boleto associado a uma fatura ao gerar uma segunda via, ou seja, se ela for acessada após a data de vencimento do boleto gerado anteriormente.
Seria isso @lucianozanita?

**Comment by lucianozanita** [comment]
A função citada é ótima, mais o ideal seria ter também uma segunda função onde que você poderia cancelar a fatura através de um botão ou informando o ID da transação do gerencianet, pois como lá não existe de forma alguma essa possibilidade de cancelar somente via api.

**Comment by mauriciogofas** [comment]
Vou estudar a possibilidade de cancelar o boleto ao cancelar a fatura, enquanto isso, [este script ](https://gist.github.com/mauriciogofas/94e37edf27ceb2d0c0d95029cacd9e80)resolve seu problema:
1) Salve o arquivo cancelatransacao.php na pasta /gofasgerencianetboleto/;
2) Substitua as credenciais e preencha o id da transação que vc deseja cancelar (linhas 6, 7 e 16);
3) Acesse https://www.seu-whmcs.com/modules/gateways/gofasgerencianetboleto/cancelatransacao.php.

**Comment by lucianozanita** [comment]
Fiz a configuração conforme me informou mais fica aparecendo "Unauthorized" mesmo o Cliente ID e Cliente Secret estando tudo certo e a ID também, você sabe o que pode ser?

**Comment by mauriciogofas** [comment]
Esqueci, tem que alterar a linha 12, deixando assim:
`'sandbox' => false`
