### ISSUE TITLE
Vencimento 

### ISSUE THREAD

**Issue by Dotsystemdigital** [gofas/whmcs-gerencianet-boleto#3]
Tem alguma opção onde eu possa colocar numero de dias a serem somados com a data de vencimento da fatura .
Ex fatura gerada dia 10 , boleto vencimento dia 13 .

acrescenta-se 3 dias da data da fatura.

**Comment by mauriciogofas** [comment]
Atualmente a data de vencimento do boleto é a mesma da fatura, mas se o cliente acessar a fatura após o vencimento, a data do boleto será a data atual(data que o cliente clicou no link da fatura) + 1 dia, se desejar que a data do vencimento do boleto seja maior nesse caso, basta editar o valor na [linha 67](https://github.com/gofas/whmcs-gerencianet-boleto/blob/master/gofasgerencianetboleto.php#L67) do arquivo gofasgerencianetboleto.php.
Original: `$billetDuedate = date('Y-m-d', strtotime('+1 day'));`
+ 3 dias: `$billetDuedate = date('Y-m-d', strtotime('+3 days'));`
