### ISSUE TITLE
Erro ao tentar usar o Gateway de Pagamento

### ISSUE THREAD

**Issue by JordanielAlves** [gofas/whmcs-gerencianet-boleto#4]
Opa, tudo bem?

Fiz os todos os procedimentos e quando clico em _Opções >> Pagamento >> Portais para Pagamento_ a tela do WHMCS fica em branco.

Será algum problema com versão do sistema? Estou utilizando a versão **6.3.1.**

Creio que não seja versão do PHP, pois o sistema está rodando normalmente. Vi que as mensagens anteriores são recentes, então creio que não seja isso...

**Comment by JordanielAlves** [comment]
Encontrei o problema. Em hospedagens como a hostgator, deve-se habilitar o suporte ao PHP Cur (5.4). 

Dentro do Cpanel, fiz isso em:

 _Advanced >> PHP Configuratiion >>_

Aponte o caminho completo do local do módulo:
_**/public_html/hospedagem/modules/gateways/gofasgerencianetboleto/**_

UPDATE

Problema resolvido!

**Comment by mauriciogofas** [comment]
Oi @JordanielAlves, tubo bem!
Não deu para responder a tempo, eu suspeitava que seria alguma incompatibilidade ou necessidade de alguma extensão, mas não conseguiria uma solução tão específica como a sua sem presenciar o erro ou sem ver os logs...
Gratidão pela contribuição!
