### ISSUE TITLE
Fatura atualizada

### ISSUE THREAD

**Issue by hostingbr** [gofas/whmcs-gerencianet-boleto#5]
Se eu acesso a fatura e gero um boleto na Gerencianet, qualquer nova modificação nessa fatura, mesmo acessando novamente a geração do boleto, não irá refletir na Gerencianet.

**Comment by mauriciogofas** [comment]
Sim, pretendo adicionar no futuro a capacidade de cancelar o boleto ao cancelar a fatura, fora isso, que tipo de alteração vc espera que seja realizado no GN ao editar a fatura?
