### ISSUE TITLE
CPF / CPNPJ

### ISSUE THREAD

**Issue by Dotsystemdigital** [gofas/whmcs-gerencianet-boleto#6]
No meu caso , quando é uma pessoa juridica , e o cliente nao coloca cpf , coloca somente o cnpj, ele nao gera o boleto aparece o erro abaixo .
Não foi possível gerar o boleto porque o seu CPF está incorreto.
Clique aqui e atualize o seu CPF, depois volte e recarregue essa página.

**Comment by mauriciogofas** [comment]
O Gerencianet exige CPF e CNPJ para gerar o boleto com o CNPJ do cliente, se preencher apenas CNPJ não vai gerar o boleto.

**Comment by tiagosjdr** [comment]
@mauriciogofas Aqui é o Tiago da Gerencianet. Agora já não é mais obrigatório o fornecimento de CPF para operação envolvendo PJ. Porém, caso você queira enviar nome e CPF, eles serão úteis para identificar sobre a pessoa física que está concretizando o pagamento em nome da empresa.

**Comment by mauriciogofas** [comment]
Bem vindo @tiagosjdr, obrigado pelo esclarecimento!
Isso é muito legal, eu e um cliente sempre passamos por essa dificuldade com os consumidores que possuem cadastro incompleto.
Vou adicionar na próxima atualização às configurações do módulo a opção de exigir ou não o CPF quando a operação envolve PJ, também vou pensar na melhor forma de evitar a exibição de erros, como por ex:
1 - gerar o boleto com CPF se o CNPJ for inválido;
2 - gerar o boleto apenas com CNPJ, se CPF for inválido.

**Comment by Dotsystemdigital** [comment]
Maravilha, pessoal , ansioso por esta atualização rsrs

 

Obrigado 

 

De: Mauricio Gofas [mailto:notifications@github.com] 
Enviada em: quarta-feira, 13 de julho de 2016 16:54
Para: gofas/whmcs-gerencianet-boleto <whmcs-gerencianet-boleto@noreply.github.com>
Cc: Dotsystemdigital <rodrigo@dotsystem.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [gofas/whmcs-gerencianet-boleto] CPF / CPNPJ (#6)

 

Bem vindo @tiagosjdr <https://github.com/tiagosjdr> , obrigado pelo esclarecimento!
Isso é muito legal, eu e um cliente sempre passamos por essa dificuldade com os consumidores que possuem cadastro incompleto.
Vou adicionar na próxima atualização às configurações do módulo a opção de exigir ou não o CPF quando a operação envolve PJ, também vou pensar na melhor forma de evitar a exibição de erros, como por ex:
1 - gerar o boleto com CPF se o CNPJ for inválido;
2 - gerar o boleto apenas com CNPJ, se CPF for inválido.

**Comment by mauriciogofas** [comment]
Adicionamos novas formas de impedir erros ao gerar Boletos devido a inconsistência no cadastro dos clientes e duas novas opções caso o admin ainda deseje exigir CPF de PJ e exibir erro no caso de CNPJ inválido, ao invés de ignorar e tentar gerar o boleto com CPF.

Todas as notas da nova versão podem ser vistas aqui:
https://github.com/gofas/whmcs-gerencianet-boleto/releases/tag/0.1.7
