### ISSUE TITLE
Erro na geração do Boleto 

### ISSUE THREAD

**Issue by Dotsystemdigital** [gofas/whmcs-gerencianet-boleto#7]
Bom dia , quando clico para gerar o boleto , para 1 cliente em especifico, ele aparece a fatura com a seguinte mensagem 
Não foi possível gerar o boleto porque o seu Nome e/ou Sobrenome estão incorretos.
Clique aqui e atualize o seu Nome/Sobrenome, depois volte e recarregue essa página.

o que pode ser ?

obrigado

**Comment by mauriciogofas** [comment]
Bom dia!
Esse erro é pq o nome e/ou sobrenome do cliente essa incompleto ou errado, verifique o nome e sobrenome no cadastro do cliente.

**Comment by mauriciogofas** [comment]
Vou fechar o issue por que não obtive resposta, se tiver algo a acrescentar vc pode comentar novamente aqui @Dotsystemdigital.
