### ISSUE TITLE
Taxas e descontos

### ISSUE THREAD

**Issue by cunningham-br** [gofas/whmcs-gerencianet-boleto#8]
Primeiramente gostaria de parabenizar pelo modulo esta perfeito 
a unica coisa que me falta seria um campo para adicionar taxas(% e valor fixo) e descontos, além de enviar o vencimento com a mesma data do vencimento do whmcs.
onde posso incluir isso?

**Comment by mauriciogofas** [comment]
Gratidão pelo feedback!
Pretendo adicionar a opção desconto/taxa até o final da próxima semana, ja tenho um beta mas ainda não deu para testar. Te aviso por aqui assim que sair a atualização.

**Comment by mauriciogofas** [comment]
@cunningham-br 
Foi adicionada a opção Taxa ou desconto na versão 0.1.8.

**Comment by cunninghambr** [comment]
@mauriciogofas perfeito so mais uma duvida 
vi que no arquivo callback poderia incluir a taxa 
como posso alterar o mesmo incluindo o valor colocado como taxa para ele no retorno pegar este valor como fee?

**Comment by mauriciogofas** [comment]
Não deu tempo de testar, mas realmente se vc associar um valor à variável `$paymentFee` o módulo vai registrar o valor abatido, mas creio que ainda precisaria inserir uma fórmula matemática para calcular e preencher o "valor de saída".
Tente adicionar este trecho à [linha 74](https://github.com/gofas/whmcs-gerencianet-boleto/blob/master/gofasgerencianetboleto/callback.php#L74) do arquivo callback.php:
`$paymentFee = '3.75'; // Altere para o valor da sua tarifa`

Vou verificar se o GN ainda não envia o _fee_, se não, vou pensar numa forma de adicionar essa opção.

**Comment by cunningham-br** [comment]
Entao to pra fazer o tete tmb nao tive tempo vou associar a variavel ja existente da taxa ao retorno e diminuir ela tmb no valor total recebido pra ficar certo
