### ISSUE TITLE
Tela branca , Portais de Pagamento

### ISSUE THREAD

**Issue by lexpo** [gofas/whmcs-gerencianet-boleto#9]
Bom dia! Amigo mandei os arquivos para o servidor conforme informado e ao entrar na pagina para selecionar o Gateways aparece uma tela branca. Renomeando para teste o arquivo gofasgerencianetboleto.php2 volta a funcionar. O que pode ser? Desde já agradeço a iniciativa.

**Comment by JordanielAlves** [comment]
Amigo, tive esse mesmo problema. Resolvi alterando a versão do php na minha hospedagem. É bem simples resolver pelo cpanel. Qualquer dúvida estamos aí.

**Comment by mauriciogofas** [comment]
Olá @lexpo, como o @JordanielAlves citou, provavelmente é alguma incompatibilidade,
se o problema persistir, ative a exibição de erros do whmcs e poste aqui o erro que for exibido na tela, por favor. Se puder enviar os logs do servidor no momento do erro seria bom para estudarmos a compatibilidade.
Vou fechar o issue mas se vc tiver mais informações pode comentar aqui.

Obrigado pela ajuda @JordanielAlves!
